# .readthedocs.yml
version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.10"
  commands:
    - pip install -r utils/requirements.txt

python:
  install:
    - requirements: utils/requirements.txt
